cubernetes/ft-transcendence

README.md
Testing signed commit + pr flow.
Added additional comments to Readme for easier work distribution.
=> Add core features to README

web/src/scripts/pages/HomePage.ts
Adds a single exclamation point to the Play Now button on button on the hero section
=> Test continuous deployment to prod with github actions

config.env
Hopefully this will work on the server, what a bizarre bug lol
=> Remove quotes in config.env (quoted env vars cause strange bugs)

.githooks/commit-msg, .githooks/disable-hooks, .githooks/enable-hooks, .githooks/pre-commit, Makefile
- Add pre-commit hook (Format staged files with prettier, abort commit when it found stuff to format)
- Add commit-msg hook (Imperative verb form in titlecase)
=> Prettier Formatting and Commit Message Pre-Commit Hooks

backend/src/controllers/websocket.controller.ts, backend/src/game/game.engine.ts, backend/src/game/game.types.ts, backend/src/models/types.ts, backend/src/services/websocket.service.ts, web/src/scripts/components/GameSection.ts
Added to class WebsocketService to start a new active connection and a game session.
On client side, keyevent is tracked and sent as move + up/down/stop if there is a change in the event.
The websocket message is then sent to the new GameEngine class to handle game logic on the server, which broadcasts back to player(s).
This is only a basic set-up which is missing many steps, but movement is tracked and the game loop is handled server side. :-)
=> Feature/websockets - basic websocket game logic communication

backend/src/ws/ws.plugin.ts, web/src/scripts/components/Footer.ts, web/src/scripts/components/GameSection.ts, web/src/scripts/components/Header.ts, web/src/scripts/pages/GamePage.ts, web/src/scripts/pages/HomePage.ts, web/src/scripts/pages/LeaderboardPage.ts, web/src/scripts/pages/ProfilePage.ts, web/src/scripts/router/Router.ts, web/src/scripts/test.ts
- Just me reviewing the entire web folder and familiarizing myself with typescript a little, this is in preparation to make hot-reloading work, but for that, I need to know a bit about the ergonomics of working with the code
- Note that this is a merge request into `feature/api+test`, not `main`
- Redirect to home when invalid route is encountered
- Redirect to home when header is clicked
- Simplify type signature of routes object by making all `create{Home,Game,Profile}Page` function async (at not cost, since `await` would wrap them in a Promise anyway later on)
=> Refactor minor web stuff

Makefile, README.md, compose.yaml, config.env, web/Caddyfile
- Clean up a few things in the repo
- Also adds some minor convenience features not worth their own PR
- Improve `fclean`, `clean` and `deepclean` targets
- Add more stuff to `README`
- Add `:8080` default port to `Caddyfile`
=> Some cleanups

app/esbuild.config.js, app/package-lock.json, app/package.json, app/reload-server.js, app/src/scripts/index.ts, compose.yaml
- Hot reload should now be working fine for index.html and any file change, addition, removal in assets directory. Likely can’t handle subdirectory, but it should work as long as everything is in root under `src/public/assets`.
- Browser now auto-refresh on any change made on the frontend.
- Rebuild on top-level change (`esbuild.config.js` and `reload-server.js` for frontend.)
=> Add watch for index.html and assets, browser hot-reload on change

.env.example, README.md, compose.yaml, config.env
- Uses a nice feature I got to know from [a friend of mine](https://github.com/mustaphazorgati/server-applications/blob/main/zorgati_cloud/compose.yml), what do you think? Reduces config duplication a bit in the yaml
=> Use yaml anchors for various things in compose.yaml

.github/workflows/npm-sync-check.yml, backend/package-lock.json
so since im new to npm and I keep forgetting to update the pckg lock if there r conflicts and I resolve them manually in the ui I added a new PR workflow check to check if the files r in sync
=> upd package lock bc I forgor

frontend/src/scripts/components/components.blockchain.ts
Fixed an issue where the game wouldn't launch if the user does not have an ethereum wallet installed.
How?
Added a try and catch and error checks to ensure wallet is initialised. If not an error is printed.
=> Fix wallet connect bug

backend/src/core/config/config.plugin.ts, compose.yaml, vault/Dockerfile, vault/entrypoint.sh, vault/policies/backend.hcl
Merge main vault PR first.
Introduces fine-grained and very restrictive policies and roles to increase security posture.
=> Add fine grained role with CIDR, max-uses, TTL, etc. restrictions

compose.yaml
Fixes some minor issues in compose.yaml (duplicate ELK, missing static IPs) and refactors it so the style is consistent throughout.
=> Refactor and fix compose.yaml

README.md
Added all of you as reviewers, please look at the percentage/notes columns for the modules that concern you again and if the percentage seems appropriate and the notes are good that just approve this pr, otherwise make a comment and I'll make a commit
=> Add progress/notes columns to tally

compose.yaml
=> Increase start_period of logstash because it's slowwww

Makefile
Forgot that it should detach too
=> Make prod should detach tho

compose.yaml
=> Remove limits to fix elk on school pc

elk/elasticsearch/Dockerfile, elk/kibana/Dockerfile, elk/kibana/config/kibana.yml, elk/logstash/Dockerfile, elk/logstash/scripts/import-logstash-ca.sh, env.json, script/find_quotes, script/quote_exceptions, vault/README.md, vault/replace_json_templates.py
Basically puts everything that was left (elk) into vault
Closes #170 
Closes #158 
Closes #157 
Closes #156 
Also cleans up some quote handling issues and updates a vault/README.md
Also fixes the way curl is downloaded in the elk containers (recent curl version "needed" for the healthchecks to work. Frankly just because I felt fancy and wanted to use a bleeding edge curl feature)
=> Move more stuff into vault & other issues

Makefile.aux
=> Use jq with a docker image

elk/elasticsearch/config/elasticsearch.yml, elk/kibana/config/kibana.yml, env.json
=> Fix env vars messyness

frontend/package-lock.json, frontend/package.json, frontend/src/scripts/modules/locale/locale.translation.ts
- Added missing translations for frontend
Fixes #164
=> Add missing translations

frontend/src/scripts/modules/locale/locale.translation.ts, frontend/src/scripts/modules/tournament/tournament.ui.ts
Add a check for the correct chain.
=> Add error check to check for correct chain id
